import { evidenceCommands } from '../audit/evidence.ts';

/**
 * Estado real de las funciones de FModel 2D CAD. Es la fuente de la pestaña «Estado de
 * funciones» de la ayuda y de docs/FEATURES.md: solo se marca «Disponible» lo que funciona
 * de extremo a extremo y está probado con evidencia comprobable.
 */
export type FeatureStatus = 'available' | 'experimental' | 'planned' | 'not-committed';

export type FeatureEvidenceKind = 'unit' | 'integration' | 'e2e' | 'manual';

export interface FeatureEvidence {
  kind: FeatureEvidenceKind;
  ref: string;
  note?: string;
}

export interface Feature {
  area: { es: string; en: string };
  name: { es: string; en: string };
  status: FeatureStatus;
  commands?: string[];
  note?: { es: string; en: string };
  evidence?: FeatureEvidence[];
}

const F = (
  areaEs: string,
  areaEn: string,
  es: string,
  en: string,
  status: FeatureStatus,
  commands?: string[],
  note?: [string, string],
  evidence?: FeatureEvidence[]
): Feature => {
  const missingCommands = status === 'available' ? (commands ?? []).filter((command) => evidenceCommands(command).length === 0) : [];
  const effectiveStatus: FeatureStatus = missingCommands.length > 0 ? 'experimental' : status;
  const evidenceNote: [string, string] | undefined = missingCommands.length > 0
    ? [
      `Evidencia ejecutada pendiente para: ${missingCommands.join(', ')}. La función no se publica como Disponible hasta enlazar cada comando a una prueba real.`,
      `Executed evidence is pending for: ${missingCommands.join(', ')}. The feature is not published as Available until every command links to a real test.`,
    ]
    : undefined;
  return {
    area: { es: areaEs, en: areaEn },
    name: { es, en },
    status: effectiveStatus,
    commands,
    note: note || evidenceNote ? { es: (note ?? evidenceNote)![0], en: (note ?? evidenceNote)![1] } : undefined,
    evidence,
  };
};

export const FEATURES: Feature[] = [
  F('Arquitectura', 'Architecture', 'Limpieza reversible de encuentros y recorte contra columnas', 'Reversible junction cleanup and column trimming', 'experimental', ['WALLCLEAN', 'WALLRESTORE'], ['ARC-007 en curso: instantánea LINE de encuentros T/X y recorte de caras contra columnas nativas. Sólo MLINE queda oculto; fuentes, IDs, grupos, parámetros y símbolos se conservan. Restaurar → editar → limpiar; Todos recupera aunque borres/desagrupes salidas. Conserva geometría editada de fuentes y salidas modificadas/ambiguas. Máximos: 100 orígenes/fragmentos, 5000 puntos, 10000 segmentos, 2000000 operaciones. Nativo conserva recuperación sin versión nueva; DXF conserva fuentes invisibles (60) y advierte pérdida de recuperación. Comandos, cinta, paleta y Arquitectura ES/EN implementados; pendiente puerta CI y revisión visual original Día/Noche escritorio/teléfono. Sin actualización automática, curvas ni paridad general YQARCH.', 'ARC-007 in progress: LINE snapshots of T/X junctions and native column face trimming. Only MLINE is hidden; source IDs, groups, parameters and symbols survive. Restore → edit → clean; All recovers erased/ungrouped outputs. Keeps edited source geometry and modified/ambiguous outputs. Limits: 100 sources/fragments, 5000 points, 10000 segments, 2000000 operations. Native preserves recovery without a format bump; DXF retains invisible sources (60) and warns of recovery loss. ES/EN commands, ribbon, palette and Architecture implemented; actual CI and raw desktop/phone Day/Night visual review remain pending. No automatic updates, curves or general YQARCH parity.'], [{ kind: 'unit', ref: 'BEH-WALL-CLEANUP' }, { kind: 'unit', ref: 'GEO-WALL-CLEANUP' }, { kind: 'integration', ref: 'IO-WALL-CLEANUP' }, { kind: 'integration', ref: 'UI-WALL-CLEANUP' }, { kind: 'e2e', ref: 'E2E-WALL-CLEANUP' }]),
  F('Arquitectura', 'Architecture', 'Relleno independiente del material de muros y columnas nativas', 'Independent native wall and column material fill', 'available', ['WALLFILL'], ['ARC-006 cerrado en este alcance: HATCH estándar Sólido/Rayado; fragmentos reales, habitaciones y huecos vacíos, columnas nativas por contorno exacto. Una confirmación/undo; sin asociación futura. Espaciado físico inicial 100 mm (0.1 m; sin unidad 100), ángulo 45°. Límites de lote y trabajo antes de vista previa/rayado. Nativo conserva origen/IDs; DXF conserva lazos y rayado de usuario, con advertencias previas de pérdida de asociación/parámetros del origen. CI 37254420973: 1297 pruebas/124 archivos, 68 recorridos Chromium (cuatro nuevos) y seis capturas originales Día/Noche/escritorio/teléfono aprobadas. No acredita paridad general YQARCH.', 'ARC-006 closed for this scope: standard Solid/Hatched HATCH; real fragments, empty rooms/openings, exact native column outlines. One confirmation/undo; no future association. Physical default spacing 100 mm (0.1 m; unitless 100), angle 45°. Batch/work bounds precede preview/hatching. Native preserves source/IDs; DXF retains loops and user hatching, with existing source association/parameter loss warnings. CI 37254420973: 1297 tests/124 files, 68 Chromium journeys (four new) and six approved original Day/Night desktop/phone captures. This does not establish general YQARCH parity.'], [{ kind: 'unit', ref: 'BEH-WALL-FILL' }, { kind: 'unit', ref: 'GEO-WALL-FILL' }, { kind: 'integration', ref: 'IO-WALL-FILL' }, { kind: 'integration', ref: 'UI-WALL-FILL' }, { kind: 'e2e', ref: 'E2E-WALL-FILL' }]),

  F('Arquitectura', 'Architecture', 'Catorce familias de construcción 2D con parámetros, grupos nativos y edición por roles', 'Fourteen 2D construction families with parameters, native groups and role-preserving edits', 'available', ['ARCHITECTURE', 'COLUMN', 'AXISGRID', 'STAIRPLAN', 'STAIRSECTION', 'ESCALATOR', 'LIFTPLAN', 'DOORELEVATION', 'DOORSECTION', 'WINDOWELEVATION', 'WINDOWSECTION', 'BAYWINDOWSECTION', 'CURTAINWALL', 'GLASSPARTITION', 'BANISTER', 'COMPONENTEDIT'], ['Medidas físicas adaptadas al documento, vista previa y undo/redo atómico. DXF conserva curvas/texto y pierde parámetros; el informe avisa. Catálogo visual con medidas/variantes y miniatura nativa. CI 37097760918: 1100 pruebas, 56 recorridos Chromium y 14 capturas Día/Noche/teléfono aprobadas para las catorce familias 2D.', 'Physical dimensions adapt to the document, with previews and atomic undo/redo. DXF keeps curves/text but loses parameters; its report warns. Visual catalogue with dimensions/variants and native miniature. CI 37097760918: 1100 tests, 56 Chromium journeys and 14 approved Day/Night/phone captures for the fourteen 2D families.'], [{ kind: 'unit', ref: 'BEH-COMPONENTS' }, { kind: 'unit', ref: 'GEO-COMPONENTS' }, { kind: 'integration', ref: 'IO-COMPONENTS' }, { kind: 'integration', ref: 'UI-COMPONENTS' }, { kind: 'e2e', ref: 'E2E-COMPONENTS' }]),
  F('Arquitectura', 'Architecture', 'Muros continuos, habitaciones, conversión de trazos rectos y huecos reales de puertas/ventanas', 'Continuous walls, rooms, straight-path conversion and real door/window openings', 'experimental', ['WALL', 'WALLRECT', 'WALLCONVERT', 'WALLDOOR', 'WALLWINDOW'], ['Muros 2D con multilíneas nativas y tapas rectas; presets físicos 100/150/200 mm. Une esquinas del mismo recorrido. Los nuevos huecos y símbolos conservan asociación nativa para mover, copiar, editar, reflejar y borrar; los grupos legados incompletos no se infieren. DXF descompone los muros en líneas y conserva tapas y símbolos. Núcleo 2D y capturas Día/Noche/teléfono aprobados en CI 37022156512.', '2D walls using native multilines with straight caps; physical 100/150/200 mm presets. Joins corners of the same path. New openings and symbols retain native association for move, copy, edit, mirror and delete; incomplete legacy groups are not inferred. DXF decomposes walls to lines and preserves caps and symbols. Core 2D and Day/Night/phone captures approved in CI 37022156512.'], [{ kind: 'unit', ref: 'BEH-ARCHITECTURE' }, { kind: 'unit', ref: 'GEO-WALLS' }, { kind: 'integration', ref: 'IO-ARCHITECTURE' }]),
  F('Arquitectura', 'Architecture', 'Ciclo de huecos asociados y espesor de muro', 'Associated opening lifecycle and wall thickness', 'available', ['OPENINGMOVE', 'OPENINGCOPY', 'OPENINGEDIT', 'OPENINGMIRROR', 'OPENINGDELETE', 'WALLTHICKNESS'], ['Muros rectos compatibles ±0.5; grupos nativos con roles/IDs estables, validación de todos los miembros y reparación del hueco anterior. Hasta 500 vértices, 200 huecos y 2000 primitivas. Sin redes T/X ni huecos curvos o de esquina; DXF conserva la geometría, pero pierde la asociación editable. CI 37131723475: 1169 pruebas, 60 recorridos Chromium y seis capturas Día/Noche/escritorio/teléfono revisadas. ARC-004 cerrado sólo en este alcance.', 'Compatible straight ±0.5 walls; native groups with stable roles/IDs, every member validated and old gap repaired. At most 500 vertices, 200 openings and 2000 primitives. No T/X networks or curved/corner openings; DXF retains geometry but loses editable association. CI 37131723475: 1169 tests, 60 Chromium journeys and six reviewed Day/Night desktop/phone captures. ARC-004 closed only for this scope.'], [{ kind: 'unit', ref: 'BEH-OPENINGS' }, { kind: 'unit', ref: 'GEO-OPENINGS' }, { kind: 'integration', ref: 'IO-OPENINGS' }, { kind: 'integration', ref: 'UI-OPENINGS' }, { kind: 'e2e', ref: 'E2E-OPENINGS' }]),
  F('Arquitectura', 'Architecture', 'Eje físico y muro paralelo por distancia libre', 'Physical wall axis and clear-gap parallel wall', 'available', ['WALLAXIS', 'WALLOFFSET'], ['ARC-005 cerrado sólo para muros rectos compatibles ±0.5: eje físico completo como polilínea independiente (hasta 500 vértices) y muro paralelo vacío por distancia libre (hasta 200). Origen y huecos intactos; default físico 1000 mm, sin unidad 1000. DXF conserva geometría nueva, pero advierte la pérdida de asociación previa del origen. CI 37169139770: 1204 pruebas, 64 recorridos Chromium y seis capturas Día/Noche/escritorio/teléfono aprobadas. Redes T/X, líneas sueltas, columnas, curvas, huecos de esquina y rellenos pendientes.', 'ARC-005 closed only for compatible straight ±0.5 walls: complete physical axis as an independent polyline (up to 500 vertices) and empty clear-gap parallel wall (up to 200). Source and openings intact; physical default 1000 mm, unitless 1000. DXF retains new geometry but warns of existing source association loss. CI 37169139770: 1204 tests, 64 Chromium journeys and six approved Day/Night desktop/phone captures. T/X networks, loose lines, columns, curves, corner openings and fills remain outstanding.'], [{ kind: 'unit', ref: 'BEH-WALL-UTILITIES' }, { kind: 'unit', ref: 'GEO-WALL-UTILITIES' }, { kind: 'integration', ref: 'IO-WALL-UTILITIES' }, { kind: 'integration', ref: 'UI-WALL-UTILITIES' }, { kind: 'e2e', ref: 'E2E-WALL-UTILITIES' }]),
  F('Geotecnia', 'Geotechnics', 'Carta de Newmark interactiva con áreas ocupadas e incremento de esfuerzo vertical', 'Interactive Newmark chart with occupied areas and vertical stress increment', 'experimental', ['NEWMARK'], ['Calcula la intersección geométrica para cimentaciones escalonadas y exporta la lámina SVG.', 'Calculates geometric intersections for stepped foundations and exports an SVG sheet.']),
  F('Lienzo', 'Canvas', 'Zoom, encuadre, extensión, zoom a selección y vistas guardadas', 'Zoom, pan, extents, zoom to selection and saved views', 'available', ['ZOOM', 'PAN', 'VIEW'], ['La rueda del ratón hace zoom y dos dedos en el panel táctil encuadran: el dispositivo se deduce del propio evento y se puede fijar a mano en Opciones › Visualización.', 'The mouse wheel zooms and two fingers on a trackpad pan: the device is inferred from the event itself and can be fixed by hand in Options › Display.'], [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Lienzo', 'Canvas', 'Rejilla, coordenadas, cruz CAD y previsualización', 'Grid, coordinates, CAD crosshair and previews', 'available', ['GRIDTOGGLE', 'DSETTINGS'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }, { kind: 'unit', ref: 'RENDER-CANVAS' }]),
  F('Lienzo', 'Canvas', 'Selección por ventana, captura, polígono, borde, tipo y capa; ciclo de selección', 'Window, crossing, polygon, fence, type and layer selection; selection cycling', 'available', ['QSELECT', 'SELECTSIMILAR'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }, { kind: 'unit', ref: 'SPATIAL-INDEX' }]),
  F('Lienzo', 'Canvas', 'Aislar, ocultar, bloquear y pantalla limpia; paneles acoplables', 'Isolate, hide, lock and clean screen; dockable panels', 'available', ['ISOLATEOBJECTS', 'HIDEOBJECTS', 'CLEANSCREENON'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }]),
  F('Lienzo', 'Canvas', 'Uso táctil: encuadre, pellizco, pulsación larga, doble pulsación, lupa al situar puntos; en el teléfono, dock flotante, tarjeta de comando con Aceptar, Cancelar y opciones, y hojas de paneles, precisión y herramientas; en la tableta, la mesa de escritorio con zoom táctil y Aceptar; el teléfono se usa en vertical y, girado, propone volver a vertical sin impedir seguir', 'Touch use: pan, pinch, long press, double tap, magnifier while placing points; on phones, a floating dock, a command card with Accept, Cancel and options, and sheets for panels, precision and tools; on tablets, the desktop workspace with touch zoom and Accept; phones are used upright and, when turned, suggest returning to portrait without forcing it', 'experimental', undefined, ['El dedo sitúa el punto con lupa y apertura ampliada; dos dedos encuadran y solo hacen zoom al separarse. Máquina de estados desacoplada en TouchGestureController con aislamiento estricto de pointercancel y rechazo de palma (3+ dedos). Probado con simulación y matriz de dispositivos en fix/features/evidence/; en teléfono el dibujo detallado sigue limitado por el tamaño de pantalla.', 'The finger places points with a magnifier and a wider aperture; two fingers pan and only zoom once separated. Decoupled state machine in TouchGestureController with strict pointercancel isolation and palm rejection (3+ fingers). Tested with simulation and device matrix in fix/features/evidence/; detailed drafting on phones remains limited by screen size.'], [{ kind: 'manual', ref: 'UI-TOUCH-MATRIX' }]),
  F('Precisión', 'Precision', 'Coordenadas absolutas, relativas y polares; distancia directa; entrada dinámica', 'Absolute, relative and polar coordinates; direct distance; dynamic input', 'available', ['DYNTOGGLE'], undefined, [{ kind: 'unit', ref: 'BEH-DRAW' }, { kind: 'unit', ref: 'GEO-INVARIANTS' }]),
  F('Precisión', 'Precision', 'Orto, rastreo polar, referencias a objetos permanentes y temporales, rastreo OTRACK, Tab entre candidatos', 'Ortho, polar tracking, running and temporary object snaps, OTRACK, Tab cycling', 'available', ['ORTHOTOGGLE', 'POLARTOGGLE', 'OSNAP', 'OTRACKTOGGLE'], undefined, [{ kind: 'unit', ref: 'BEH-DRAW' }, { kind: 'unit', ref: 'GEO-CURVES' }]),
  F('Dibujo', 'Draw', 'Línea, polilínea, círculo, arco, rectángulo, polígono, elipse, spline, punto, rayo, línea auxiliar, nube de revisión, arandela', 'Line, polyline, circle, arc, rectangle, polygon, ellipse, spline, point, ray, xline, revision cloud, donut', 'available', ['LINE', 'PLINE', 'CIRCLE', 'ARC', 'RECTANG', 'POLYGON', 'ELLIPSE', 'SPLINE', 'POINT', 'RAY', 'XLINE', 'REVCLOUD', 'DONUT'], undefined, [{ kind: 'unit', ref: 'BEH-DRAW' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Dibujo', 'Draw', 'Sombreado con islas, contorno, región, cobertura, multilínea, dividir y medir', 'Hatch with islands, boundary, region, wipeout, multiline, divide and measure', 'available', ['HATCH', 'BOUNDARY', 'REGION', 'WIPEOUT', 'MLINE', 'DIVIDE', 'MEASURE'], undefined, [{ kind: 'unit', ref: 'BEH-DRAW' }, { kind: 'unit', ref: 'GEO-CURVES' }]),
  F('Dibujo', 'Draw', 'Texto, texto de párrafos, directriz múltiple y tabla', 'Text, mtext, multileader and table', 'available', ['TEXT', 'MTEXT', 'MLEADER', 'TABLE'], undefined, [{ kind: 'unit', ref: 'BEH-ANNOTATE' }]),
  F('Dibujo', 'Draw', 'Curvas de enlace tangentes (G1) o suaves con curvatura continua (G2) entre dos objetos', 'Tangent (G1) or smooth curvature-continuous (G2) blend curves between two objects', 'experimental', ['BLEND'], ['Crea una spline de Bézier sujeta, exportable a DXF sin pérdida.', 'Creates a clamped Bézier spline, exportable to DXF without loss.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }, { kind: 'unit', ref: 'GEO-BLEND' }]),
  F('Modificar', 'Modify', 'Borrar, desplazar, copiar, girar, escalar, simetría, desfase, recortar, alargar, empalme, chaflán, estirar', 'Erase, move, copy, rotate, scale, mirror, offset, trim, extend, fillet, chamfer, stretch', 'available', ['ERASE', 'MOVE', 'COPY', 'ROTATE', 'SCALE', 'MIRROR', 'OFFSET', 'TRIM', 'EXTEND', 'FILLET', 'CHAMFER', 'STRETCH'], undefined, [{ kind: 'unit', ref: 'BEH-MODIFY' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Modificar', 'Modify', 'Matrices rectangular, polar y por trayectoria (asociativas)', 'Rectangular, polar and path arrays (associative)', 'available', ['ARRAYRECT', 'ARRAYPOLAR', 'ARRAYPATH'], undefined, [{ kind: 'unit', ref: 'BEH-MODIFY' }]),
  F('Modificar', 'Modify', 'Juntar, partir, partir en punto, descomponer, editar polilínea, longitud, alinear, invertir, orden de dibujo, grupos, operaciones booleanas', 'Join, break, break at point, explode, edit polyline, lengthen, align, reverse, draw order, groups, booleans', 'available', ['JOIN', 'BREAK', 'BREAKATPOINT', 'EXPLODE', 'PEDIT', 'LENGTHEN', 'ALIGN', 'REVERSE', 'DRAWORDER', 'GROUP', 'UNION'], undefined, [{ kind: 'unit', ref: 'BEH-MODIFY' }, { kind: 'unit', ref: 'GEO-INVARIANTS' }]),
  F('Capas y propiedades', 'Layers and properties', 'Administrador de capas: estados, filtros, aislar, fusionar, congelación por viewport; herencia PorCapa/PorBloque', 'Layer manager: states, filters, isolate, merge, per-viewport freeze; ByLayer/ByBlock inheritance', 'available', ['LAYER', 'LAYERSTATE', 'LAYISO', 'LAYMRG', 'VPLAYER'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }]),
  F('Capas y propiedades', 'Layers and properties', 'Inspector de propiedades con edición por lotes e igualar propiedades', 'Properties inspector with batch editing and match properties', 'available', ['PROPERTIES', 'MATCHPROP'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }]),
  F('Capas y propiedades', 'Layers and properties', 'Copiar objetos a otra capa y recorrer las capas una a una', 'Copy objects to another layer and walk layers one at a time', 'experimental', ['COPYTOLAYER', 'LAYWALK'], ['LAYWALK solo cambia la vista y la restaura al salir.', 'LAYWALK only changes the view and restores it on exit.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }]),
  F('Anotación', 'Annotation', 'Estilos de texto, cota, directriz múltiple, tabla y multilínea; lista de escalas', 'Text, dimension, multileader, table and multiline styles; scale list', 'available', ['STYLE', 'SCALELISTEDIT'], undefined, [{ kind: 'unit', ref: 'BEH-ANNOTATE' }]),
  F('Anotación', 'Annotation', 'Cotas lineales, alineadas, angulares, radio, diámetro, arco, coordenada, continuas y de línea base; asociativas', 'Linear, aligned, angular, radius, diameter, arc, ordinate, continue and baseline dimensions; associative', 'available', ['DIMLINEAR', 'DIMALIGNED', 'DIMANGULAR', 'DIMRADIUS', 'DIMDIAMETER', 'DIMARC', 'DIMORDINATE', 'DIMCONTINUE', 'DIMBASELINE'], undefined, [{ kind: 'unit', ref: 'BEH-ANNOTATE' }]),
  F('Anotación', 'Annotation', 'Campos, tolerancias, prefijos/sufijos, unidades alternativas y escala anotativa', 'Fields, tolerances, prefix/suffix, alternate units and annotative scale', 'available', ['FIELD'], undefined, [{ kind: 'unit', ref: 'BEH-ANNOTATE' }]),
  F('Anotación', 'Annotation', 'Acotación rápida en cadena, línea base, coordenadas, radio y diámetro; espaciado y cortes de cota', 'Quick dimensioning as chain, baseline, ordinate, radius and diameter; dimension spacing and breaks', 'experimental', ['QDIM', 'DIMSPACE', 'DIMBREAK'], ['Las cotas de QDIM son asociativas. Los cortes automáticos se recalculan al mover la cota o lo que la cruza; los manuales no.', 'QDIM dimensions are associative. Automatic breaks are recomputed when the dimension or what crosses it moves; manual ones are not.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }, { kind: 'unit', ref: 'ANNOT-LAYOUT' }]),
  F('Anotación', 'Annotation', 'Marcas y ejes de centro asociativos', 'Associative center marks and centerlines', 'experimental', ['CENTERMARK', 'CENTERLINE'], ['Siguen al círculo, arco o tramos de origen; si se copian o se mueven por su cuenta quedan independientes. DXF las exporta como líneas.', 'They follow the source circle, arc or segments; if copied or moved on their own they become independent. DXF exports them as lines.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }, { kind: 'integration', ref: 'IO-NATIVE' }]),
  F('Anotación', 'Annotation', 'Texto de una línea a texto múltiple y alineación o distribución de textos', 'Single-line text to Mtext and text alignment or distribution', 'experimental', ['TXT2MTXT', 'TEXTALIGN'], ['TXT2MTXT combina de arriba abajo y conserva barras, llaves y campos.', 'TXT2MTXT combines top to bottom and keeps backslashes, braces and fields.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }]),
  F('Bloques', 'Blocks', 'Definiciones, inserción con autoescala, atributos y extracción', 'Definitions, insertion with unit scaling, attributes and extraction', 'available', ['BLOCK', 'INSERT', 'ATTDEF', 'ATTEDIT', 'DATAEXTRACTION'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }, { kind: 'unit', ref: 'IO-CLIPBOARD' }]),
  F('Bloques', 'Blocks', 'Biblioteca por categorías con etiquetas, importación desde DXF (bloques o dibujo entero) y bibliotecas compartibles .fmodellib', 'Categorized library with tags, import from DXF (blocks or whole drawing) and shareable .fmodellib libraries', 'available', ['LIBRARYIMPORT', 'LIBRARYEXPORT', 'WBLOCK'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Bloques', 'Blocks', 'Hacer estirable cualquier bloque: Ancho y Fondo para alargarlo, acortarlo, ensancharlo o estrecharlo sin deformar lo que no cruza el corte', 'Make any block stretchable: Width and Depth to lengthen, shorten, widen or narrow it without distorting what does not cross the cut', 'available', ['BESTIRABLE'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Bloques', 'Blocks', 'Biblioteca inicial: 100 bloques de LibreCAD (GPL-2.0) y 12 muebles paramétricos (clósets que añaden hojas, mesa que añade sillas, cama con anchos estándar…)', 'Starter library: 100 LibreCAD blocks (GPL-2.0) and 12 parametric furniture pieces (closets that add doors, table that adds chairs, bed with standard widths…)', 'available', ['LIBRARYSTARTER'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Bloques', 'Blocks', 'Biblioteca integrada: 398 bloques CAD 2D en formato nativo de FModel, con unidades y miniaturas', 'Built-in library: 398 2D CAD blocks in FModel native format, with units and thumbnails', 'available', undefined, undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Bloques', 'Blocks', 'Bloques dinámicos: parámetros, acciones, estados de visibilidad, tablas de consulta, fórmulas y variables', 'Dynamic blocks: parameters, actions, visibility states, lookup tables, formulas and variables', 'available', ['BEDIT', 'BPARAMETER', 'BACTION', 'BVSTATE', 'BVARIABLE'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }, { kind: 'unit', ref: 'IO-DXF' }]),
  F('Bloques', 'Blocks', 'Editor de bloques con prueba, edición en contexto, validación y vista previa en vivo', 'Block editor with testing, in-place editing, validation and live preview', 'available', ['BEDIT', 'BTESTBLOCK', 'BCLOSE'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Paramétrico', 'Parametric', 'Restricciones geométricas en el dibujo (coincidente, horizontal, vertical, paralela, perpendicular, tangente, concéntrica, igual, simétrica, colineal, fija) con inferencia automática', 'Drawing geometric constraints (coincident, horizontal, vertical, parallel, perpendicular, tangent, concentric, equal, symmetric, collinear, fix) with automatic inference', 'experimental', ['GEOMCONSTRAINT', 'AUTOCONSTRAIN', 'DELCONSTRAINT', 'CONSTRAINTBAR', 'CONSTRAINTINFER'], ['Un reactor transaccional mantiene la geometría resuelta dentro de la misma transacción que la edita (un solo paso de deshacer). Al mover un objeto, lo unido lo sigue; «Fija» impide que el solver lo mueva pero no bloquea MOVE. Se guardan en .fmodel v4; DXF las exporta como geometría fija y lo avisa.', 'A transactional reactor keeps geometry solved inside the same transaction that edits it (one undo step). Moving an object drags what is joined to it; «Fix» keeps the solver from moving it but does not block MOVE. Saved in .fmodel v4; DXF exports them as fixed geometry and says so.'], [{ kind: 'unit', ref: 'BEH-PARAMETRIC' }, { kind: 'unit', ref: 'PARAMETRIC-MODEL' }, { kind: 'unit', ref: 'SOLVER-CONSTRAINTS' }]),
  F('Paramétrico', 'Parametric', 'Cotas de restricción con nombre y fórmula, parámetros de usuario, variantes y conversión de cotas asociativas', 'Named constraint dimensions with formulas, user parameters, variants and associative dimension conversion', 'experimental', ['DIMCONSTRAINT', 'PARAMETERS', 'PARAMEDIT'], ['Cambiar un valor mueve el segundo punto de la cota y deja anclado el primero; un valor sin solución, un ciclo o una fórmula inválida se rechazan sin tocar el dibujo. Renombrar actualiza las fórmulas y variantes que lo usan.', 'Changing a value moves the second point of the dimension and keeps the first anchored; an unsolvable value, a cycle or an invalid formula is rejected without touching the drawing. Renaming updates the formulas and variants that use it.'], [{ kind: 'unit', ref: 'BEH-PARAMETRIC' }, { kind: 'unit', ref: 'PARAMETRIC-MODEL' }, { kind: 'integration', ref: 'IO-NATIVE' }]),
  F('Bloques', 'Blocks', 'Restricciones geométricas y dimensionales dentro de bloques, con glifos, cotas de restricción y conflictos en el lienzo', 'Geometric and dimensional constraints inside blocks, with glyphs, constraint dimensions and conflicts on canvas', 'available', ['BCONSTRAINT', 'BCPARAMETER'], ['Resolvedor numérico por mínimos cuadrados amortiguados: las restricciones incompatibles se marcan en conflicto en lugar de ignorarse.', 'Damped least-squares numeric solver: incompatible constraints are flagged as conflicts instead of being ignored.'], [{ kind: 'unit', ref: 'SOLVER-CONSTRAINTS' }]),
  F('Paletas', 'Palettes', 'Paletas de herramientas con categorías, favoritos, búsqueda y arrastrar y soltar', 'Tool palettes with categories, favorites, search and drag and drop', 'available', ['TOOLPALETTES'], undefined, [{ kind: 'unit', ref: 'BEH-LIBRARY' }]),
  F('Presentaciones', 'Layouts', 'Presentaciones, viewports rectangulares, poligonales y de objeto, escala bloqueada, capas por viewport', 'Layouts, rectangular, polygonal and object viewports, locked scale, per-viewport layers', 'available', ['LAYOUT', 'MVIEW', 'MSPACE', 'PSPACE', 'VPSCALE', 'VPLOCK'], undefined, [{ kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }, { kind: 'unit', ref: 'RENDER-CANVAS' }]),
  F('Presentaciones', 'Layouts', 'Configuración de página, cajetín con campos', 'Page setup, title block with fields', 'available', ['PAGESETUP', 'TITLEBLOCK'], undefined, [{ kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Salida', 'Output', 'PDF vectorial por hoja y publicación multipágina; monocromo y escala de grises; grosores', 'Vector PDF per sheet and multi-page publishing; monochrome and grayscale; lineweights', 'available', ['PLOT', 'EXPORTPDF', 'PUBLISH'], undefined, [{ kind: 'unit', ref: 'RENDER-CANVAS' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Salida', 'Output', 'SVG en milímetros', 'Millimetre SVG', 'available', ['EXPORTSVG'], undefined, [{ kind: 'unit', ref: 'RENDER-CANVAS' }]),
  F('Intercambio', 'Interchange', 'Formato nativo versionado .fmodel y JSON de depuración', 'Versioned native .fmodel format and debug JSON', 'available', ['QSAVE', 'SAVEAS', 'OPEN', 'EXPORTJSON'], undefined, [{ kind: 'unit', ref: 'IO-NATIVE' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Intercambio', 'Interchange', 'Importación y exportación DXF con informe de conversión', 'DXF import and export with conversion report', 'available', ['IMPORTDXF', 'EXPORTDXF'], ['Detalle en docs/dxf-compatibilidad.md. Los bloques dinámicos de FModel sobreviven a la ida y vuelta.', 'Details in docs/dxf-compatibilidad.md. FModel dynamic blocks survive the round trip.'], [{ kind: 'unit', ref: 'IO-DXF' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Intercambio', 'Interchange', 'CSV/JSON de atributos y tablas', 'Attribute and table CSV/JSON', 'available', ['DATAEXTRACTION'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }]),
  F('Intercambio', 'Interchange', 'Lectura experimental de DWG (abrir e importar a la biblioteca)', 'Experimental DWG reading (open and import to the library)', 'experimental', ['OPEN', 'LIBRARYIMPORT'], ['Probada con DWG de AutoCAD 2000 y 2018 frente a su DXF equivalente. El lector local se carga solo al abrir el primer archivo.', 'Tested with AutoCAD 2000 and 2018 DWG against their equivalent DXF. The local reader loads only when opening the first file.'], [{ kind: 'unit', ref: 'DWG-EXPERIMENTAL' }]),
  F('Intercambio', 'Interchange', 'Bloques dinámicos de AutoCAD desde DXF o DWG: parámetros lineal, de punto, rotación, simetría, visibilidad y punto base con acciones desplazar, estirar, escalar, girar y simetría', 'AutoCAD dynamic blocks from DXF or DWG: linear, point, rotation, flip, visibility and base point parameters with move, stretch, scale, rotate and flip actions', 'experimental', ['OPEN', 'IMPORTDXF', 'LIBRARYIMPORT'], ['Formato no documentado: cada tipo se verifica comparando las instancias con la geometría que guarda AutoCAD, con muestras de un único origen (ACadSharp). Consulta, XY, polar, alineación y matrices dinámicas se importan como geometría estática y el informe lo explica.', 'Undocumented format: each type is verified by comparing instances with the geometry AutoCAD stores, with samples from a single source (ACadSharp). Lookup, XY, polar, alignment and dynamic arrays import as static geometry and the report says so.'], [{ kind: 'unit', ref: 'IO-DXF' }]),
  F('Intercambio', 'Interchange', 'Escritura DWG', 'DWG writing', 'not-committed', undefined, ['FModel no escribe DWG: exporta DXF.', 'FModel does not write DWG: export DXF.']),
  F('Referencias', 'References', 'Dibujos referenciados (enlazar/superponer), recarga, descarga, apertura, unión, ruta, detección de ciclos', 'Referenced drawings (attach/overlay), reload, unload, open, bind, repath, cycle detection', 'available', ['XATTACH', 'XREFMANAGER', 'XRELOAD', 'XOPEN', 'XBIND', 'XREPATH'], undefined, [{ kind: 'unit', ref: 'BEH-REFERENCES' }]),
  F('Referencias', 'References', 'Imágenes y calcos PDF con recorte, opacidad, atenuación y bloqueo', 'Images and PDF underlays with clip, opacity, fade and lock', 'available', ['IMAGEATTACH', 'PDFATTACH', 'IMAGECLIP', 'IMAGEADJUST'], undefined, [{ kind: 'unit', ref: 'BEH-REFERENCES' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Referencias', 'References', 'Referencias a objetos sobre la geometría de calcos PDF', 'Object snaps on PDF underlay geometry', 'available', undefined, ['Se extraen los trazos vectoriales de la página (no el texto ni las imágenes rasterizadas); las curvas se aproximan con tramos rectos.', 'Vector strokes of the page are extracted (not text or raster images); curves are approximated with straight segments.'], [{ kind: 'unit', ref: 'BEH-REFERENCES' }]),
  F('Calidad', 'Quality', 'Auditoría con corrección, informe de salud, limpieza de duplicados y elementos sin uso', 'Audit with fixes, health report, duplicate and unused cleanup', 'available', ['AUDIT', 'HEALTHREPORT', 'OVERKILL', 'PURGE'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }, { kind: 'unit', ref: 'WORKER-ASYNC' }]),
  F('Calidad', 'Quality', 'Comparación de revisiones', 'Revision comparison', 'available', ['COMPARE'], undefined, [{ kind: 'unit', ref: 'BEH-MANAGEMENT' }]),
  F('Calidad', 'Quality', 'Propiedades de masa: área, centroide, inercias, producto de inercia, ejes principales y radios de giro', 'Mass properties: area, centroid, inertia, product of inertia, principal axes and radii of gyration', 'experimental', ['MASSPROP'], ['Integración exacta en líneas y arcos (Green + Gauss-Legendre); huecos restados por anidamiento; splines aproximadas y avisadas.', 'Exact integration on lines and arcs (Green + Gauss-Legendre); holes subtracted by nesting; splines approximated and flagged.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }, { kind: 'unit', ref: 'GEO-MASSPROP' }]),
  F('Productividad', 'Productivity', 'Paleta de comandos, alias y atajos configurables, repetir último, favoritos, propiedades rápidas, historial de comandos y ayuda contextual', 'Command palette, configurable aliases and shortcuts, repeat last, favorites, quick properties, command history and contextual help', 'available', ['OPTIONS', 'HELP', 'QUICKPROPERTIES', 'TEXTSCR'], undefined, [{ kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }, { kind: 'unit', ref: 'UI-A11Y' }]),
  F('Productividad', 'Productivity', 'Autoguardado, recuperación tras cierre y versiones locales', 'Autosave, crash recovery and local versions', 'available', ['VERSIONS', 'RECOVER'], undefined, [{ kind: 'unit', ref: 'STORAGE-PERSISTENCE' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Productividad', 'Productivity', 'Español e inglés', 'Spanish and English', 'available', ['OPTIONS'], undefined, [{ kind: 'unit', ref: 'UI-A11Y' }]),
  F('Productividad', 'Productivity', 'Aplicación instalable con uso sin conexión (PWA) y apertura de .fmodel/.dxf desde el sistema', 'Installable app with offline use (PWA) and opening .fmodel/.dxf from the system', 'experimental', ['UPDATEAPP'], ['El service worker precarga toda la versión y está cubierto por pruebas; la instalación y la apertura de archivos dependen del navegador (Safari no abre archivos desde el sistema).', 'The service worker precaches the whole version and is covered by tests; installation and file opening depend on the browser (Safari does not open files from the system).'], [{ kind: 'unit', ref: 'PWA-SW' }, { kind: 'e2e', ref: 'E2E-CRITICAL-JOURNEYS' }]),
  F('Productividad', 'Productivity', 'Copiar con punto base, pegar en coordenadas originales y pegar como bloque', 'Copy with base point, paste to original coordinates and paste as block', 'experimental', ['COPYBASE', 'PASTEORIG', 'PASTEBLOCK'], ['PASTEORIG se rechaza en el mismo dibujo de origen para no duplicar objetos encima.', 'PASTEORIG is refused in the source drawing to avoid duplicating objects on top.'], [{ kind: 'unit', ref: 'BEH-PRODUCTION' }]),
  F('Rendimiento', 'Performance', 'Índice espacial, renderizado por lotes con caché de trazados', 'Spatial index, batched rendering with path cache', 'available', undefined, undefined, [{ kind: 'unit', ref: 'SPATIAL-INDEX' }, { kind: 'unit', ref: 'RENDER-CANVAS' }]),
  F('Rendimiento', 'Performance', 'Lectura y exportación DXF y análisis de salud en segundo plano (Web Worker)', 'DXF reading and export and health analysis in the background (Web Worker)', 'available', ['OPEN', 'EXPORTDXF', 'AUDIT', 'HEALTHREPORT'], ['Si el navegador no permite workers se ejecutan en el hilo principal con el mismo resultado.', 'If the browser disallows workers they run on the main thread with the same result.'], [{ kind: 'unit', ref: 'WORKER-ASYNC' }]),
];

export const STATUS_LABEL: Record<FeatureStatus, { es: string; en: string; tone: string }> = {
  available: { es: 'Disponible', en: 'Available', tone: 'disponible' },
  experimental: { es: 'Experimental', en: 'Experimental', tone: 'experimental' },
  planned: { es: 'Planeado', en: 'Planned', tone: 'planeado' },
  'not-committed': { es: 'No comprometido', en: 'Not committed', tone: 'no-comprometido' },
};
