import { expect, it } from 'vitest';
import { CommandHarness } from '../commands/behavior/harness';
import { FORMAT_VERSION, fromNativeFile, toNativeFile } from './native';
import { createDocument } from '../document/defaults';
import { Editor } from '../editor/editor';
import { translation } from '../geometry/matrix';
it('round-trips v6 dimensions, migrates v5 independently and preserves geometry on broken references', async () => {
  const h = new CommandHarness();
  await h.run('WALL', [{ x: 0, y: 0 }, { x: 6000, y: 0 }, '']);
  const wall = [...h.doc.data.entities.values()][0];
  h.select(wall.id);
  await h.run('WALLDIM', ['', '', '']);
  const file = toNativeFile(h.doc.data, h.doc.id);
  expect(FORMAT_VERSION).toBe(6);
  const loaded = fromNativeFile(file), editor = new Editor(createDocument());
  editor.doc.replaceData(loaded.data, loaded.documentId);
  const ids = [...editor.doc.data.entities.values()].filter(e => e.type === 'dimension').map(e => e.id);
  editor.transformEntities([wall.id], translation(500, 0), 'MOVE');
  expect(editor.doc.entity(ids[0])).toMatchObject({ p1: { x: 500, y: 0 } });
  const invalid = structuredClone(file);
  (invalid.collections.groups!.find((g: any) => g.automation) as any).automation.version = 2;
  expect(() => fromNativeFile(invalid)).toThrow();
  const broken = structuredClone(file);
  (broken.collections.groups!.find((g: any) => g.automation) as any).automation.style = 'missing';
  const repaired = fromNativeFile(broken);
  expect([...repaired.data.groups.values()].some(g => g.automation)).toBe(false);
  expect(repaired.data.entities.has(ids[0])).toBe(true);
  expect(repaired.warnings.join(' ')).toMatch(/conservad|preserved/);
  file.version = 5;
  expect([...fromNativeFile(file).data.groups.values()].some(g => g.automation)).toBe(false);
  expect(() => fromNativeFile({ ...file, version: 7 })).toThrow();
});
it('repairs broken network references without losing faces or hidden native sources', async () => {
  const h = new CommandHarness();
  await h.run('WALL', [{ x: 0, y: 0 }, { x: 6000, y: 0 }, '']);
  const wall = [...h.doc.data.entities.values()][0];
  await h.run('WALLAUTO', ['Solid', '']);
  const file = toNativeFile(h.doc.data, h.doc.id), group = file.collections.groups!.find((g: any) => g.automation) as any;
  group.automation.sourceForOutput[group.members[0]] = 'missing';
  const loaded = fromNativeFile(file);
  expect(loaded.data.entities.get(wall.id)?.visible).toBe(true);
  expect(loaded.data.entities.has(group.members[0])).toBe(true);
  expect(loaded.data.groups.get(group.id)?.automation).toBeUndefined();
  const wrong = structuredClone(file);
  (wrong.collections.groups!.find((g: any) => g.automation) as any).automation.fill = ['solid'];
  expect(() => fromNativeFile(wrong)).toThrow();
});
