import { expect, it, vi } from 'vitest';
import { CadDocument } from '../document/document';
import { createDocument } from '../document/defaults';
import type { LineEntity, LwPolylineEntity, MLineEntity } from '../document/types';
import { wallFaces } from '../geometry/walls';
import { readWallSource } from '../model/wallAssembly';
import { createContext } from '../model/context';
import { CommandHarness } from '../commands/behavior/harness';
import { exportDxf } from './dxf/exportDxf';
import { importDxfIntoDocument } from './dxf/importDxf';
import { readPackage, writePackage } from './native';

const p = (x: number, y = 0) => ({ x, y });
it('wall utilities retain native standard geometry and source association while DXF keeps the real face distance', async () => {
  vi.spyOn(console, 'error').mockImplementation(() => {});
  const h = new CommandHarness();
  expect((await h.run('WALL', [p(0), p(6000), ''])).ok).toBe(true);
  const sourceId = [...h.doc.data.entities.values()].find(e => e.type === 'mline')!.id;
  expect((await h.run('WALLDOOR', [p(3000, 75), p(3000), p(3000, 1000), ''])).ok).toBe(true);
  const associated = readWallSource(h.doc, sourceId).assembly!;
  const sourceBefore = new Map(associated.members.map(id => [id, h.doc.entity(id)]));
  const axisRun = h.runner.execute('WALLAXIS');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('entity')); h.runner.submitEntity(associated.members.at(-1)!, p(0));
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword')); h.runner.submitText(''); await axisRun;
  const offsetRun = h.runner.execute('WALLOFFSET');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('entity')); h.runner.submitEntity(sourceId, p(0));
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('distance')); h.runner.submitText('1000');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('point')); h.runner.submitText('Left');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword')); h.runner.submitText(''); await offsetRun;
  const axis = [...h.doc.data.entities.values()].find((e): e is LwPolylineEntity => e.type === 'lwpolyline')!;
  const copy = [...h.doc.data.entities.values()].find((e): e is MLineEntity => e.type === 'mline' && !associated.members.includes(e.id))!;
  expect(axis.vertices).toEqual([{ ...p(0), bulge: 0, startWidth: 0, endWidth: 0 }, { ...p(6000), bulge: 0, startWidth: 0, endWidth: 0 }]);
  expect(copy.vertices).toEqual([p(0, 1150), p(6000, 1150)]);
  expect(copy.meta?.fmodelWallMember).toBeUndefined();
  expect(new Map([...sourceBefore.keys()].map(id => [id, h.doc.entity(id)]))).toEqual(sourceBefore);
  const loaded = readPackage(writePackage(h.doc.data, h.doc.id));
  const reopened = new CadDocument(loaded.data, loaded.documentId);
  expect(loaded.warnings).toEqual([]);
  expect(reopened.entity(axis.id)).toEqual(axis); expect(reopened.entity(copy.id)).toEqual(copy);
  expect(readWallSource(reopened, sourceId).assembly).toEqual(associated);
  const exported = exportDxf(h.doc, createContext(h.doc));
  expect(exported.report.transformed.FMODELWALLASSEMBLY?.count).toBe(1);
  expect(exported.report.transformed.FMODELWALLUTILITIES).toBeUndefined();
  const imported = createDocument(); const report = importDxfIntoDocument(imported, exported.text, { replace: true });
  expect(report.ignored).toEqual({});
  const lines = [...imported.data.entities.values()].filter((e): e is LineEntity => e.type === 'line');
  const faces = wallFaces(copy);
  expect(faces[1][0].y).toBe(1075);
  expect(lines.some(line => [line.start.y, line.end.y].every(y => Math.abs(y - 1075) < 1e-7))).toBe(true);
  const importedAxis = [...imported.data.entities.values()].find((e): e is LwPolylineEntity => e.type === 'lwpolyline' && e.vertices.length === 2 && e.vertices.every(v => Math.abs(v.y) < 1e-7))!;
  expect(importedAxis.vertices.map(v => ({ x: v.x, y: v.y }))).toEqual([p(0), p(6000)]);
});
