import { expect, it, vi } from 'vitest';
import { CommandHarness } from './harness';
import { fromNativeFile, toNativeFile } from '../../io/native';
import { Editor } from '../../editor/editor';
import { CadDocument } from '../../document/document';
import { hatchPolygons } from '../../model/hatchPatterns';
import { createLayer, mergeLayers } from '../../layers/layerOps';
import { readWallAssembly } from '../../model/wallAssembly';
it('live T junction and fill follow native opening edits, new neighbors and undo; edited outputs survive disabling', async () => {
  const h = new CommandHarness();
  await h.run('WALL', [{ x: 0, y: 0 }, { x: 6000, y: 0 }, '']);
  const wall = [...h.doc.data.entities.values()][0];
  await h.run('WALL', [{ x: 3000, y: 0 }, { x: 3000, y: 3000 }, '']);
  const before = new Map(h.doc.data.entities);
  expect((await h.run('WALLAUTO', ['Solid', ''])).ok).toBe(true);
  const network = () => [...h.doc.data.groups.values()].find(g => g.automation?.kind === 'wall-network')!;
  expect(h.doc.entity(wall.id)?.visible).toBe(false);
  expect([...h.doc.data.entities.values()].some(e => e.type === 'hatch')).toBe(true);
  h.undo();
  expect(h.doc.data.entities).toEqual(before);
  h.redo();
  const link = network().automation!;
  if (link.kind !== 'wall-network')
    throw new Error('network');
  const face = Object.entries(link.sourceForOutput).find(([id, source]) => source === wall.id && h.doc.entity(id)?.type === 'line')![0];
  const run = h.runner.execute('WALLDOOR');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('entity'));
  h.runner.submitEntity(face, { x: 1000, y: 0 });
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('point'));
  h.runner.submitPoint({ x: 1000, y: 0 });
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('point'));
  h.runner.submitText('');
  await run;
  expect(readWallAssembly(h.doc, wall.id).openings).toHaveLength(1);
  expect(network().automation?.status).toBeUndefined();
  const a = readWallAssembly(h.doc, wall.id), leaf = [...a.roles.entries()].find(([role]) => role.includes("leaf"))![1];
  const edit = h.runner.execute('OPENINGEDIT');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('entity'));
  h.runner.submitEntity(leaf, { x: 1000, y: 0 });
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword'));
  h.runner.submitText('Width');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('distance'));
  h.runner.submitText('1100');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword'));
  h.runner.submitText('');
  await edit;
  expect(readWallAssembly(h.doc, wall.id).openings[0].width).toBe(1100);
  const prior = new Map(h.doc.data.entities);
  const move=h.runner.execute('WALLMOVE');await vi.waitFor(()=>expect(h.runner.pending?.req.kind).toBe('entity'));h.runner.submitEntity(face,{x:0,y:0});
  await vi.waitFor(()=>expect(h.runner.pending?.req.kind).toBe('point'));h.runner.submitPoint({x:0,y:0});await vi.waitFor(()=>expect(h.runner.pending?.req.kind).toBe('point'));h.runner.submitPoint({x:0,y:400});await move;
  expect(readWallAssembly(h.doc, wall.id).source.vertices[0].y).toBe(400);
  expect(network().automation?.status).toBeUndefined();
  h.undo();
  expect(h.doc.data.entities).toEqual(prior);
  h.doc.transact('secondary group',tx=>tx.add('groups',{id:'secondary',name:'User group',description:'',members:[wall.id],selectable:true}));
  const erase=h.runner.execute('WALLERASE');await vi.waitFor(()=>expect(h.runner.pending?.req.kind).toBe('entity'));h.runner.submitEntity(face,{x:0,y:0});await vi.waitFor(()=>expect(h.runner.pending?.req.kind).toBe('keyword'));h.runner.submitText('');await erase;
  expect(h.doc.entity(wall.id)).toBeUndefined();
  expect(h.doc.data.groups.get('secondary')?.members).toEqual([]);
  expect(network().automation?.status).toBeUndefined();
  h.undo();
  expect(h.doc.data.entities).toEqual(prior);
  const sourceBefore = new Map(h.doc.data.entities);
  await h.run('WALL', [{ x: 0, y: 1000 }, { x: 6000, y: 1000 }, '']);
  const expanded = network().automation;
  expect(expanded?.kind === 'wall-network' && Object.keys(expanded.hidden).length).toBeGreaterThan(2);
  h.undo();
  expect(h.doc.data.entities).toEqual(sourceBefore);
  const loaded = new CommandHarness(new Editor(new CadDocument(fromNativeFile(toNativeFile(h.doc.data, h.doc.id)).data)));
  const g = [...loaded.doc.data.groups.values()].find(g => g.automation?.kind === 'wall-network')!;
  const id = g.members.find(id => loaded.doc.entity(id)?.type === 'line')!, e = loaded.doc.entity(id)!;
  loaded.doc.transact('manual line', tx => tx.updateEntity(id, { color: '#ff0000' }));
  const edited = loaded.doc.entity(id);
  expect((await loaded.run('WALLAUTO', ['Off', ''])).ok).toBe(true);
  expect(loaded.doc.entity(id)).toEqual(edited);
  expect(loaded.doc.entity(wall.id)?.visible).toBe(true);
  expect(loaded.doc.entity(id)).not.toEqual(e);
});
it('closed walls retain the room void and do not reveal previously hidden sources', async () => {
  const h = new CommandHarness();
  await h.run('WALLRECT', [{ x: 0, y: 0 }, { x: 4000, y: 3000 }]);
  const room = [...h.doc.data.entities.values()][0];
  await h.run('WALL', [{ x: 5000, y: 0 }, { x: 7000, y: 0 }, '']);
  const hidden = [...h.doc.data.entities.values()].find(e => e.id !== room.id)!;
  h.doc.transact('hide source', tx => tx.updateEntity(hidden.id, { visible: false }));
  await h.run('WALLAUTO', ['Solid', '']);
  const hatch = [...h.doc.data.entities.values()].find(e => e.type === 'hatch')!;
  expect(hatch.type === 'hatch' && hatch.loops.length).toBe(2);
  if (hatch.type === 'hatch')
    expect(hatchPolygons(hatch.loops, 'normal')).toHaveLength(2);
  const g = [...h.doc.data.groups.values()].find(g => g.automation?.kind === 'wall-network')!;
  expect(g.automation?.kind === 'wall-network' && Object.hasOwn(g.automation.hidden, hidden.id)).toBe(false);
  await h.run('WALLAUTO', ['Off', '']);
  expect(h.doc.entity(hidden.id)?.visible).toBe(false);
});
it('merging a source layer retains generated IDs without duplicates', async () => {
  const h = new CommandHarness();
  const layer = h.doc.transact('layer', tx => createLayer(tx, h.doc, { name:'Muros' }));
  h.doc.transact('current', tx => tx.setSettings({ currentLayer: layer.id }));
  await h.run('WALL', [{ x: 0, y: 0 }, { x: 6000, y: 0 }, '']);
  await h.run('WALLAUTO', ['Solid', '']);
  const ids = [...h.doc.data.entities.keys()], g = [...h.doc.data.groups.values()].find(g => g.automation?.kind === 'wall-network')!, members = [...g.members];
  h.doc.transact('merge layer', tx => mergeLayers(tx, h.doc, [layer.id], 'layer-0'));
  expect([...h.doc.data.entities.keys()]).toEqual(ids);
  expect(h.doc.data.groups.get(g.id)?.members).toEqual(members);
  expect(h.doc.entity(ids[0])?.layer).toBe('layer-0');
});
it('cancels live network preview without hiding walls or retaining outputs', async () => {
  const h = new CommandHarness();
  await h.run('WALL', [{ x: 0, y: 0 }, { x: 6000, y: 0 }, '']);
  const before = new Map(h.doc.data.entities), run = h.runner.execute('WALLAUTO');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword'));
  h.runner.submitText('Solid');
  await vi.waitFor(() => expect(h.runner.pending?.req.kind).toBe('keyword'));
  h.runner.cancel();
  await run;
  expect(h.doc.data.entities).toEqual(before);
  expect([...h.doc.data.groups.values()].some(g => g.automation)).toBe(false);
});
